Django-Series/Django-Series/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^Myseriesapp/',include('myseriesapp.urls', namespace='myseriesapp')),
    url(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
]

Django-Series/myseriesapp/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login,logout
from myseriesapp import views
from myseriesapp.views import Animes, Series, Productoras

urlpatterns = [
    url(r'series/', Series.as_view(), name='series'),
    url(r'animes/', Animes.as_view(), name='animes'),
    url(r'^inicio/', views.inicio, name='inicio'),
    url(r'productoras/', Productoras.as_view(), name='productoras'),
    url(r'^perfil/$', views.perfil, name='perfil'),
    url(r'^login$',login, {'template_name' : 'login.html', }, name='login'),
    url(r'^logout$',logout, {'next_page': 'myseriesapp:inicio', }, name='logout'),
    url(r'^signup$', views.signup, name='Registrarse'),
    url(r'^detalle/serie/(?P<serie_id>\d+)/$', views.serie_nombre,name='serie_nombre'),
    url(r'^detalle/anime/(?P<anime_id>\d+)/$', views.anime_nombre,name='anime_nombre'),
    url(r'registro_serie/$', views.register_serie, name='registro_serie'),
    url(r'registro_anime/$', views.register_anime, name='registro_anime'),
    url(r'registro_productora/$', views.register_productora, name='registro_productora'),
]

Django-Series/myseriesapp/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Productora(models.Model):
	nombre=models.CharField(max_length=50)
	año_fundacion=models.DateField()
	web=models.CharField(max_length=100)
	def __str__(self):
		return self.nombre

class Serie(models.Model):
	nombre=models.CharField(max_length=50, unique=True)
	año_lanzamiento=models.DateField()
	descripcion=RichTextField(max_length=5000)
	imagen=models.ImageField(upload_to='series/')
	productora=models.ForeignKey(Productora,null=True)
	def __str__(self):
		return self.nombre + ", " + str(self.año_lanzamiento)

class Anime(models.Model):
	nombre=models.CharField(max_length=50, unique=True)
	año_lanzamiento=models.DateField()
	descripcion=RichTextField(max_length=5000)
	imagen=models.ImageField(upload_to='animes/')
	productora=models.ForeignKey(Productora,null=True)
	def __str__(self):
		return self.nombre + ", " + str(self.año_lanzamiento)

class User_image(models.Model):
	usuario=models.OneToOneField(User,null=False,on_delete=models.CASCADE, primary_key=True)
	imagen=models.ImageField(upload_to='user_images/')
	def __str__(self):
		return "imagen de " + self.usuario.username

class Nota_serie(models.Model):
	usuario=models.ForeignKey(User,null=False, on_delete=models.CASCADE)
	serie=models.ForeignKey(Serie,null=False, on_delete=models.CASCADE)
	nota=models.FloatField()
	def __str__(self):
		return self.usuario + " " + self.serie.nombre + ": " + str(self.puntuacion)

class Nota_anime(models.Model):
	class Meta:
		unique_together = ('usuario','anime',)
	usuario=models.ForeignKey(User,null=False, on_delete=models.CASCADE)
	anime=models.ForeignKey(Anime,null=False, on_delete=models.CASCADE)
	nota=models.FloatField()
	def __str__(self):
		return self.usuario.username + " " + self.anime.nombre + ": " + str(self.nota)

Django-Series/myseriesapp/forms.py
from django import forms
from myseriesapp.models import Serie, Productora, Anime
from ckeditor.fields import RichTextField

class SerieForm(forms.Form):
    nombre=forms.CharField(max_length=50,label='Nombre')
    año_lanzamiento=forms.DateField(widget=forms.SelectDateWidget(years=range(1950,2017)))
    descripcion=forms.CharField(max_length=5000,label='descripcion')
    imagen=forms.ImageField(widget=forms.FileInput,required=False)
    productora=forms.ModelChoiceField(queryset=Productora.objects.all())

class AnimeForm(forms.Form):
    nombre=forms.CharField(max_length=50,label='Nombre')
    año_lanzamiento=forms.DateField(widget=forms.SelectDateWidget(years=range(1960,2017)))
    descripcion=forms.CharField(max_length=5000,label='descripcion')
    imagen=forms.ImageField(widget=forms.FileInput,required=False)
    productora=forms.ModelChoiceField(queryset=Productora.objects.all())

class ProductoraForm(forms.Form):
    nombre=forms.CharField(max_length=50,label='Nombre')
    año_fundacion=forms.DateField(widget=forms.SelectDateWidget(years=range(1920,2017)))
    web=forms.CharField(max_length=100,label='web')

class SignUpForm(forms.Form):
    username=forms.CharField(max_length=30,label='Nombre de usuario')
    password=forms.CharField(max_length=30,label='Contraseña', widget=forms.PasswordInput())
    email=forms.CharField(max_length=50,label='Correo electrónico')
    first_name=forms.CharField(max_length=30,label='Nombre')
    last_name=forms.CharField(max_length=30,label='Apellido')

class PerfilImagenForm(forms.Form):
    imagen=forms.ImageField(widget=forms.FileInput,required=False)

class RateSerieForm(forms.Form):
    nota=forms.FloatField()

    def clean_nota(self):
        if self.cleaned_data['nota'] >= 10 or self.cleaned_data['nota'] <= 0:
            raise forms.ValidationError("La nota tiene que estar entre 0 y 10")
        return self.cleaned_data['nota']

class RateAnimeForm(forms.Form):
    nota=forms.FloatField()
    def clean_nota(self):
        if self.cleaned_data['nota'] >= 10 or self.cleaned_data['nota'] <= 0:
            raise forms.ValidationError("La nota tiene que estar entre 0 y 10")
        return self.cleaned_data['nota']

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True, label="Nombre")
    contact_email = forms.EmailField(required=True, label="Email")
    content = forms.CharField(required=True,widget=forms.Textarea, label="Mensaje"
    )

Django-Series/myseriesapp/views.py
from django.shortcuts import render, render_to_response
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
import datetime
from django.template.context import RequestContext
from myseriesapp.models import Serie, Productora, Anime, Nota_anime,Nota_serie,User_image
from myseriesapp.forms import SerieForm, ProductoraForm, SignUpForm, AnimeForm, RateSerieForm, RateAnimeForm, PerfilImagenForm, ContactForm
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.contrib.auth.forms import AuthenticationForm
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template

# Create your views here.
class Series(ListView):
	model=Serie
	template_name ='series.html'

class Animes(ListView):
    model=Anime
    template_name='animes.html'

class Productoras(ListView):
    model=Productora
    template_name ='productoras.html'

def serie_nombre(request, serie_id):
    serie=Serie.objects.get(pk=serie_id)
    if request.method == 'POST':
        form = RateSerieForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            usuario = request.user
            nota=cd['nota']
            registro = Nota_serie(usuario=usuario,serie=serie, nota=nota)
            try:
                registro.save()
            except:
                registro=Nota_serie.objects.filter(usuario=usuario,anime=anime).update(nota=nota)
            return HttpResponseRedirect('../'+serie_id)
    else:
        form = RateSerieForm()
    try:
        notas_serie=Nota_serie.objects.filter(serie=serie)
        suma=0
        cont=0
        for nota in notas_serie:
            cont+=1
            suma=suma+nota.nota
        if cont > 0:
            nota_serie=suma/cont
        else:
            nota_serie="Aún no hay puntuaciones"
    except Serie.DoesNotExist:
        raise Http404("La serie no existe")
    context={'serie' : serie, 'nota' : nota_serie, 'form' : form}
    return render(request,"detalle_serie.html",context)

def anime_nombre(request, anime_id):
    anime=Anime.objects.get(pk=anime_id)
    if request.method == 'POST':
        form = RateAnimeForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            usuario = request.user
            nota=cd['nota']
            registro = Nota_anime(usuario=usuario,anime=anime, nota=nota)
            try:
                registro.save()
            except:
                registro=Nota_anime.objects.filter(usuario=usuario,anime=anime).update(nota=nota)
            return HttpResponseRedirect('../'+anime_id)
    else:
        form = RateAnimeForm()
    try:
        notas_anime=Nota_anime.objects.filter(anime=anime)
        suma=0
        cont=0
        for nota in notas_anime:
            cont+=1
            suma=suma+nota.nota
        if cont > 0:
            nota_anime=suma/cont
        else:
            nota_anime="Aún no hay puntuaciones"
    except Anime.DoesNotExist:
        raise Http404("El anime no existe")

    context={'anime' : anime, 'nota' : nota_anime, 'form' : form}
    return render(request,"detalle_anime.html",context)

def register_serie(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            form = SerieForm(request.POST, request.FILES)
            if form.is_valid():
                cd = form.cleaned_data
                nombre=cd['nombre']
                año_lanzamiento=cd['año_lanzamiento']
                descripcion=cd['descripcion']
                imagen=cd['imagen']
                productora=cd['productora']
                serie = Serie(nombre=nombre,año_lanzamiento=año_lanzamiento,descripcion=descripcion,imagen=imagen, productora=productora)
                serie.save()
                return HttpResponseRedirect('../series')
        else:
            form = SerieForm()
        return render(request, 'registro.html', {'form': form, 'type' : 'serie'})
    else:
        return HttpResponseRedirect(reverse('myseriesapp:login'))


def register_anime(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            form = AnimeForm(request.POST, request.FILES)
            if form.is_valid():
                cd = form.cleaned_data
                nombre=cd['nombre']
                año_lanzamiento=cd['año_lanzamiento']
                descripcion=cd['descripcion']
                imagen=cd['imagen']
                productora=cd['productora']
                anime = Anime(nombre=nombre,año_lanzamiento=año_lanzamiento,descripcion=descripcion,imagen=imagen, productora=productora)
                anime.save()
                return HttpResponseRedirect('../animes/')
        else:
            form = AnimeForm()
        return render(request, 'registro.html', {'form': form, 'type' : 'anime'})
    else:
        return HttpResponseRedirect(reverse('myseriesapp:login'))


def register_productora(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            form = ProductoraForm(request.POST, request.FILES)
            if form.is_valid():
                cd = form.cleaned_data
                nombre=cd['nombre']
                año_fundacion=cd['año_fundacion']
                web=cd['web']
                productora = Productora(nombre=nombre,año_fundacion=año_fundacion,web=web)
                productora.save()
                return HttpResponseRedirect('../productoras/')
        else:
            form = ProductoraForm()
        return render(request, 'registro.html', {'form': form})
    else:
        return HttpResponseRedirect(reverse('myseriesapp:login'))

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd["username"]
            password = cd["password"]
            email = cd["email"]
            first_name = cd["first_name"]
            last_name = cd["last_name"]
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            return HttpResponseRedirect(reverse('myseriesapp:login'))
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def perfil(request):
    if request.user.is_authenticated():
        usuario = request.user
        if request.method == 'POST':
            form = PerfilImagenForm(request.POST, request.FILES)
            if form.is_valid():
                cd = form.cleaned_data
                imagen = cd['imagen']
                user_image=User_image(usuario=usuario,imagen=imagen)
                user_image.save()
                return HttpResponseRedirect(reverse('myseriesapp:perfil'))
        else:
            form = PerfilImagenForm()
        try:
            user_image = User_image.objects.get(usuario=usuario)
            context={'usuario' : usuario, 'form' : form, 'imagen' : user_image.imagen}
        except:
            context={'usuario' : usuario, 'form' : form}
        
        return render(request,"perfil.html",context)
    else:
        return HttpResponseRedirect(reverse('myseriesapp:login'))

def inicio(request):
    form_class = ContactForm
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'contact_name'
            , '')
            contact_email = request.POST.get(
                'contact_email'
            , '')
            form_content = request.POST.get('content', '')

            # Email the profile with the 
            # contact information
            template = get_template('contact_template.txt')
            context = Context({
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content,
            })
            content = template.render(context)

            email = EmailMessage(
                "Mensaje de contacto",
                content,
                "Myseriesapp" +'',
                ['myseriesapp@gmail.com'],
                headers = {'Reply-To': contact_email }
            )
            email.send()
            return redirect('myseriesapp:inicio')
    return render(request, 'index.html', {
        'form': form_class,
    })

Django-Series/myseriesapp/templates/animes.html
{% extends "base.html" %}

{% block title %}

	Animes

{% endblock %}

{% block javascript %}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script>
		$(document).ready(function(){
    		$("#mostrar").click(function(){
        	$(".imagen").show(1000);
    	});
    		$("#ocultar").click(function(){
        	$(".imagen").hide(1000);
    	});
		});
	</script>

{% endblock %}
 
{% block content %} 

<div class="content-wrapper">
    <section class="primary" id="contenido">
        <div class="container">
        	<ul class="list-group">
				{% for anime in object_list %}
					<section class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-0 col-md-4">
						<li id="cardseries" class="list-group-item">
							<a class="imagen" href="../detalle/anime/{{anime.id}}"> <img src="../../static/images/{{anime.imagen}}" width="320" height="200"></a>
							<h4><strong>{{anime.nombre}}</strong></h4>
							<h5>fecha de publicación: {{anime.año_lanzamiento}} </h5>
						</li>
					</section>
				{% endfor %}
			</ul>
		</div>
    </section>
</div>

{% endblock %}

Django-Series/myseriesapp/templates/base.html
<html>
<head>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
	{% block javascript %}
	{% endblock %}
	<title>{% block title %} {% endblock %} </title>
</head>
<body>
    	{% load staticfiles %}
    		<header>
    			<div class="navbar-wrapper">
    			    <div class="container-fluid">
    			        <nav class="navbar navbar-fixed-top">
    			            <div class="container">
    			                <div class="navbar-header">
    			                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
    			                        <span class="sr-only">Toggle navigation</span>
    			                        <span class="icon-bar"></span>
    			                        <span class="icon-bar"></span>
    			                        <span class="icon-bar"></span>
    			                    </button>
    			                    <a class="navbar-brand" href='{% url "myseriesapp:inicio" %}'><img class="logo" src="{% static 'images/logo.png' %}"/></a>
    			                </div>
    			                <div id="navbar" class="navbar-collapse collapse">
    			                    <ul class="nav navbar-nav">
    			                    <li><a href='{% url "myseriesapp:inicio" %}'>inicio</a></li>
                                    <li><a href='{% url "myseriesapp:series" %}'>series</a></li>
                                    <li><a href='{% url "myseriesapp:animes" %}'>animes</a></li>
                                    <li><a href='{% url "myseriesapp:productoras" %}'>productoras</a></li>
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">añadir
                                        <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                          <li><a href='{% url "myseriesapp:registro_serie" %}'>serie</a></li>
                                          <li><a href='{% url "myseriesapp:registro_anime" %}'>anime</a></li>
                                          <li><a href='{% url "myseriesapp:registro_productora" %}'>productora</a></li>
                                        </ul>
                                    </li>
                                    </ul>
                                    <ul class="nav navbar-nav pull-right">
                                    {% if user.is_authenticated %}
                                        <li class="dropdown">
                                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{user.username}}<span class="caret"></span></a>
                                            <ul class="dropdown-menu">
                                                <li><a href='{% url "myseriesapp:perfil" %}'>Mi perfil <span class="glyphicon glyphicon-user"></a></li>
                                                <li><a href='{% url "myseriesapp:logout" %}'>salir <span class="glyphicon glyphicon-log-out"></a></li>
                                            </ul>
                                        </li>
                                    {% else %}
                                        <li class=""><a href='{% url "myseriesapp:login" %}'"><span class="glyphicon glyphicon-log-in"> login</a></li>
                                    {% endif %}
                                    </ul>
    			                </div>
    			            </div>
    			        </nav>
    			    </div>
    			</div>
    		</header>

	{% block content %}

	{% endblock %}

	<footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h4> Contenido principal </h4>
                    <ul>
                        <li> <a href='{% url "myseriesapp:series" %}'> Series </a> </li>
                        <li> <a href='{% url "myseriesapp:animes" %}'> Animes </a> </li>
                        <li> <a href='{% url "myseriesapp:productoras" %}'> Productoras </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h4> Interactua </h4>
                    <ul>
                        <li> <a href='{% url "myseriesapp:registro_serie" %}'> Añadir serie </a> </li>
                        <li> <a href='{% url "myseriesapp:registro_anime" %}'> Añadir anime </a> </li>
                        <li> <a href='{% url "myseriesapp:registro_productora" %}'> Añadir productora </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h4> A tu alcance </h4>
                    <ul>
                        <li> <a href='{% url "myseriesapp:perfil" %}'> Perfil </a> </li>
                        <li> <a href='{% url "myseriesapp:inicio" %}#contact'> Contacta </a> </li>
                        <li> <a href='{% url "myseriesapp:inicio" %}'> Inicio </a> </li>
                    </ul>
                </div>
                <div class="col-lg-offset-3 col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                    <h4> Visita nuestras redes sociales </h4>
                    <ul class="social">
                        <li> <a href="https://www.facebook.com/"> <i class=" fa fa-facebook">   </i> </a> </li>
                        <li> <a href="https://twitter.com/"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="https://plus.google.com/?hl=es"> <i class="fa fa-google-plus">   </i> </a> </li>
                        <li> <a href="https://www.youtube.com/"> <i class="fa fa-youtube">   </i> </a> </li>
                        <li> <a href="https://www.instagram.com/?hl=es"> <i class="fa fa-instagram">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row--> 
        </div>
        <!--/.container--> 
    </div>
    <!--/.footer-->
    
    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © Mario Ponce García 2017. All right reserved. </p>
        </div>
    </div>
    <!--/.footer-bottom--> 
</footer>
</body>

Django-Series/myseriesapp/templates/detalle_anime.html
{% extends "base.html" %}

{% block title %}

	{{anime.nombre}}

{% endblock %}

{% block javascript %}
	<script>
		$(document).ready(function(){
	    	$("#botonPuntuar").click(function(){
	        	$("#divform").fadeIn("slow");
	    	});
		});
    </script>

{% endblock %}
 
{% block content %}
	<div class="content-wrapper select">
        <div class="container">
        	<div id="detalleSerie" class="col-md-8 col-md-offset-2">
	        	<img class="img-thumbnail" id="imgdescripcion" src="../../../../static/images/{{anime.imagen}}" width="600" height="380">
	            <h1>  
					{{anime.nombre}}
				</h1>
				<hr class="star-primary">
				<h3>
					<strong>Puntuación:</strong> {{nota|floatformat:2}}
				</h3>
				<h4>
					<strong>Lanzamiento:</strong> {{anime.año_lanzamiento}}
				</h4>
				<p>
					<strong>Productora:</strong> {{anime.productora}}
				</p>
				<p>
					{{anime.descripcion | safe}}
				</p>
				{% if user.is_authenticated %}
				<div>
					<button class="btn btn-default" id="botonPuntuar">Puntuar <span class="glyphicon glyphicon-chevron-down"></button>
				</div>
				<div id="divform" class="col-md-6 col-md-offset-3">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data" role="form">
						{% load bootstrap %}
						{% csrf_token %}
						{{ form|bootstrap_horizontal }}
						<input type="submit" class="btn-success" value="confirmar">
					</form>
				</div>
				{% endif %}
			</div>
        </div>
    </div>
{% endblock %}

Django-Series/myseriesapp/templates/detalle_serie.html
{% extends "base.html" %}

{% block title %}

	{{serie.nombre}}

{% endblock %}

{% block javascript %}
	<script>
		$(document).ready(function(){
	    	$("#botonPuntuar").click(function(){
	        	$("#divform").fadeIn("slow");
	    	});
		});
    </script>

{% endblock %}
 
{% block content %}
	<div class="content-wrapper select">
        <div class="container">
        	<div id="detalleSerie" class="col-md-8 col-md-offset-2">
	        	<img class="img-thumbnail" id="imgdescripcion" src="../../../../static/images/{{serie.imagen}}" width="600" height="380">
	            <h1>  
					{{serie.nombre}}
				</h1>
				<hr class="star-primary">
				<h3>
					<strong>puntuación:</strong> {{nota|floatformat:2}}
				</h3>
				<h4>
					<strong>lanzamiento:</strong> {{serie.año_lanzamiento}}
				</h4>
				<p>
					<strong>productora:</strong> {{serie.productora}}
				</p>
				<p>
					{{serie.descripcion | safe}}
				</p>
				{% if user.is_authenticated %}
				<div>
					<button class="btn btn-default" id="botonPuntuar">Puntuar <span class="glyphicon glyphicon-chevron-down"></button>
				</div>
				<div id="divform" class="col-md-6 col-md-offset-3">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data" role="form">
						{% load bootstrap %}
						{% csrf_token %}
						{{ form|bootstrap_horizontal }}
						<input type="submit" class="btn-success" value="confirmar">
					</form>
				</div>
				{% endif %}
			</div>
			</div>
        </div>
    </div>
{% endblock %}

 

Django-Series/myseriesapp/templates/login.html
{% extends 'base.html' %}

{% block title %} login {% endblock %}

{% block content %}
    <section class="primary" id="contenido">
    <div class="container">
            <br>
            <div class="row">
                <div class="col-xs-6 col-xs-offset-3 col-dg-6 col-dg-offset-3 col-md-4 col-md-offset-4">
                    <div class="login-panel panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">login</h3>
                        </div>
                        <div class="panel-body">
                            <form role="form" method="post" id='form_login' action="">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>Usuario:</label>
                                    </br>
                                    {{ form.username }}
                                </div>
                                <div class="form-group">
                                    <label>Contraseña:</label>
                                    </br>
                                    {{ form.password }}
                                </div>
                                <button class="btn btn-lg btn-success btn-block" type="submit" name="login"/>Login</button>
                            </form>
                        </div>
                    </div>
                    <p class="enlaceRegistro">¿Aún no tienes cuenta? registrate <a href="{% url 'myseriesapp:Registrarse' %}">aquí</a><p>
                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissable fade in">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>Error</strong> Porfavor introduzca un usuario y contraseña correctos
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        </section>
 
{% endblock %}

Django-Series/myseriesapp/templates/perfil.html
{% extends "base.html" %}

{% block title %}

  Animes

{% endblock %}

{% block content %} 
  <div class="content-wrapper select">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">INFORMACION PERSONAL</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="{% if imagen %} ../../static/images/{{imagen}} {% else %} ../../static/images/perfil-default.jpg {% endif %}" class="img-circle img-responsive">
                </div>
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>NOMBRE DE CUENTA:</td>
                        <td>{{usuario.first_name}}</td>
                      </tr>
                      <tr>
                        <td>EMAIL:</td>
                        <td>{{usuario.email}}</td>
                      </tr>
                      <tr>
                        <td>NOMBRE:</td>
                        <td>{{usuario.first_name}}</td>
                      </tr>
                      <tr>
                        <td>APELLIDO:</td>
                        <td>{{usuario.last_name}}</td>
                      </tr>                
                    </tbody>
                  </table>               
                </div>
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" role="form">
                  {% csrf_token %}
                  {{ form.imagen }}
                  <input type="submit" class="btn-success" value="confirmar">
                </form>
              </div>
            </div>                  
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}